export default  {
    ADD_TASK: 'ADD_TASK',
    ADD_ALL: 'ADD_ALL',
    DELETE_TASK: 'DELETE_TASK',
    UPDATE_TASK: 'UPDATE_TASK',
  
    SET_INPUT_DESCRIPTION: 'SET_INPUT_DESCRIPTION',
    SET_INPUT_DATE: 'SET_INPUT_DATE',
    SET_INPUT_TIME: 'SET_INPUT_TIME',
    SET_INPUT_ID: 'SET_INPUT_ID',
    RESET_INPUT: 'RESET_INPUT',
  }